### PR TITLE
import option values instead of hardcoding them

### LINKED ISSUE #1: Implement web interface for DB
Should have a form page that a user can fill out to add a candle to the database.

### PR DESCRIPTION
**Pull request by JuliaBrandenberger**
closes #1

### CODE REVIEW

**Review by colinlogue — CHANGES_REQUESTED** [review]
Could you refactor so that these use a shared component for the selects?

**Comment by JuliaBrandenberger** [comment]
added a dropdown component

**Review by colinlogue — CHANGES_REQUESTED** [review]
Still need to use form data to update database after it's submitted.

**Review by colinlogue — APPROVED** [review]

**Comment by colinlogue** [comment]
closes #4

**Pull request merged**
